# Generated by Django 5.2.5 on 2025-08-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiDlaKrzysia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listazadan',
            name='expirationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listazadan',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listazadan',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
