# Generated by Django 5.2.5 on 2025-08-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiDlaKrzysia', '0002_listazadan_expirationdate_listazadan_iscompleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listazadan',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Expired', 'expired')], default='Active', max_length=20),
        ),
    ]
